apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        interval: ${interval}
        path: ${path}
        prune: ${prune}
        decryption:
          provider: sops
          secretRef:
            name: ${decryption_secret}
    target:
      kind: Kustomization
      name: flux-system
